name: Nightly Build

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch: # to enable manual trigger

permissions:
  contents: read

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.example .env

      - name: Start the app
        run: docker compose up -d --build

      - name: Run Database Migrations
        run: docker compose exec web alembic upgrade head

      - name: Run Tests
        run: docker compose exec web pytest
        continue-on-error: false

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub
        if: success()
        run: |
          docker tag fastapi-beyond-crud-web:latest ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-web:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-web:latest
          docker tag fastapi-beyond-crud-celery:latest ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-celery:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-crud-celery:latest

  handle-build-failure:
    needs: build-test-and-push
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Email Notification (Ethereal)
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: maynard.fay@ethereal.email
          password: HHvj9VW59c5Z1hGxGU
          subject: "Nightly Build Failed!"
          to: email@example.com
          from: "GitHub Actions <no-reply@example.com>"
          body: "The nightly build for the main branch has failed."